### ISSUE TITLE
Better formatting for whois information

### ISSUE THREAD

**Issue by eritbh** [r-anime/misato#47]
- [x] #107 Use full URLs for Reddit usernames so they can be clicked to check their profile
- [x] Include times in note/warn/ban/etc display
- [x] #188 Indicate whether user is still in server
- [x] #185 Show usernames and discriminators

**Comment by bernasx** [comment]
Just adding this to remind us to always display the discrim is the .whois due to mods using IDs and others not being able to immediately tell who they're warning. Good QoL feature.

**Comment by bernasx** [comment]
Also we should add if the user is or is not in the server at the time of the command, zerotsu does it and like the above, it's helpful

**Comment by eritbh** [comment]
Links to Reddit profiles were added in #107, other improvements still stand.

I'd also like to make a single list of kicks/bans/etc rather than splitting them up, but #94 needs to happen before that.

**Comment by mushroom-disaster** [comment]
> Also we should add if the user is or is not in the server at the time of the command, zerotsu does it and like the above, it's helpful
I've made a pull request for this
#188

**Comment by eritbh** [comment]
Updated issue description to reflect what changes have been made here. Since it looks like we've done everything that's come up, closing this for now and if we want to make more improvements we can throw them in other issues or just make PRs for them without an issue.
